apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kpcea-testing
  namespace: argocd
spec:
  project: default
  destination:
    namespace: kpcea-test
    server: https://kubernetes.default.svc
  source:
    path: helm-guestbook
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
    automated:
      prune: false
      selfHeal: false
